### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by sdcooke** [Khan/tinyquery#1]
Are you interested in or currently working on python 3 support? I could potentially find the time to do the conversion (maybe using `six` if necessary) if you're open to it.

**Comment by kevinbarabash** [comment]
@sdcooke we're using GAE which currently doesn't have support for python 3 so I don't think we'd want this change at this particular moment.  Thanks for checking first.

**Comment by sdcooke** [comment]
I may fork and give it a go anyway because that might be less effort than making my own bigquery mock! If it involves minimal changes that work on python 2 I'll open a PR but feel free to close if that doesn't work for you.

**Comment by sdcooke** [comment]
I've got the tests passing on python 3 - it took more changes than I'd hoped (https://github.com/Khan/tinyquery/compare/master...mixcloud:py3) so I doubt you'll want to pull them in. Will test against actual code rather than just tests tomorrow.

Tests took 70% of the time on python 3!

**Comment by sdcooke** [comment]
Thank you for creating this library!

I've split up the changes as suggested - I was on autopilot so didn't think of some of your safer suggestions. For now I've opened some PRs on my fork because it's a little confusing (I've branched off branches).

I think these two shouldn't be too controversial:
 * Imports: https://github.com/mixcloud/tinyquery/pull/1
 * List comprehensions: https://github.com/mixcloud/tinyquery/pull/4

For string handling I've got:
 * WIthout six: https://github.com/mixcloud/tinyquery/pull/2
 * With six: https://github.com/mixcloud/tinyquery/pull/3 (`six.string_types`, despite being plural, isn't a list in either python 2 or 3)
At runtime this should be exactly the same in python 2.

Initially I wanted to avoid using six if possible and managed to continue on to:  
 * Iterators: https://github.com/mixcloud/tinyquery/pull/5 (it looked like all uses of `itervalues()` and `iteritems()` were on columns or small numbers of items (mostly columns) so I've just converted all to `values()` and `items()`)
 * zip: https://github.com/mixcloud/tinyquery/pull/7 (in my change in `repeated_util.py` isn't ideal but the context doesn't look particularly optimised so I assume it's operating on small numbers of items. Most other uses of zip happen to work because they are iterated)

Unfortunately I couldn't find a good way to avoid `six` (or adding a helper function) to get around `xrange`: https://github.com/mixcloud/tinyquery/pull/6

Once I had added `six` for that I figured it made sense to use it for the string stuff.

There are conflicts between those branches so to test against python 3 I created an `allpy3` branch that merges them all together.

From my point of view, if you're not able to merge all of these I'll still need to keep a fork (the library we're testing needs to be on python 3 for the performance it brings) but the fewer differences there are the better! If you're able to merge them all we can just make sure we test against python 3 before upgrading and open PRs if python 3 compatibility is lost, that way you won't need to worry too much about it.

Let me know what you'd like me to do.

**Comment by csilvers** [comment]
I apologize it's taken me so long to respond!  I have no good excuse. :-(

I'm not sure what you had in mind as next steps?  Was it just to look at each of these PRs and give a verbal OK or no, and if it's ok you'd make a PR against the Khan version?  Or were you just going to merge these into your own fork and try to merge the entire fork back to Khan?

I'd be happy with the former!  Maybe it's not too hard to do; I can try if you'd like.

In any case, I looked through all of the changes and they all look good to me; I've approved them.

**Comment by sdcooke** [comment]
No worries - I know it's time consuming dealing with open source projects! We're pip installing our fork for now so it's not holding us back.

I think my reasoning was that because these PRs branch off each other and have some merge conflicts along the way it might be easiest if I separated into PRs for review then opened a single PR with everything. I've just looked at your commit messages and you have a pretty specific format so now I'm wondering what the best approach is - happy to do whatever you need. I can open a web of PRs for the separate branches, I can squash commits before if you need, whatever! Let me know and I'll sort it out.

**Comment by csilvers** [comment]
The specific format is just because internal development uses phabricator for code reviews instead of github.  You don't need to worry about that.

What would be most useful to me is if you created new PRs with branches off of Khan/tinyquery, one for each PR you have now.  I'll aim to approve and merge them pretty quickly -- should be easy since they're already reviewed -- so you can just start with a few that don't conflict with each other, and then make the new ones after those are in.  That way you don't have to worry about merge conflicts.

Ideally the code in the new PRs will be exactly the same as the ones in the current PRs, so I can just glance through them for review.  If you do need to make any changes, just point them out in comments and I'll look at those more carefully.

Sound good?

**Comment by sdcooke** [comment]
I've opened PRs for everything that was branched off master - nothing is changed from https://github.com/mixcloud/tinyquery/pull/4, https://github.com/mixcloud/tinyquery/pull/2, and https://github.com/mixcloud/tinyquery/pull/1 - I just had to create new branch names because github wouldn't let me use the same ones. Once those are merged I'll open PRs for the branches that depend on the comprehensions branch.

**Comment by csilvers** [comment]
OK, merged them all -- thanks much!

**Comment by sdcooke** [comment]
This should be the final PR - the test suite passes on python 3 on this branch https://github.com/Khan/tinyquery/pull/12

Thank you!

**Comment by makearl** [comment]
Will there be a package released with the Python3 updates? The last release I see on PyPI is version 1.1

**Comment by csilvers** [comment]
OK, I just released v1.2, which should have the python3 support.  Let me know how it works!

**Comment by makearl** [comment]
Works great so far, thank you!
