### ISSUE TITLE
Extending SQL support

### ISSUE THREAD

**Issue by billonahill** [Khan/tinyquery#15]
I've been looking for a mock implementation of the newer BigQuery Cloud Client (versus the Google API Client that tinyquery uses[1]) and Tinyquery is the closest I've found. This is really cool!

I was considering extending it to include an interface for the new client, but there are quite a few SQL features that we also need. For example support for `CREATE TABLE`, `INSERT`, `FULL OUTER JOIN`. Do you know if anyone has done any work in this area? I'd be glad to contribute but I'm trying to assess just how much work we'd need to put in to meet our needs. It would be great to be able to run tests without a dep on the actual BigQuery service.

1 - https://cloud.google.com/apis/docs/client-libraries-explained

**Comment by csilvers** [comment]
I think this project has no active development at this point, and I don't know if anyone who follows it is really up on it enough to do good code reviews.  But we'd be very happy to accept patches anyway!, and do the best we can with them.

I think the tinyquery was written before google supported standard sql, so it might be a lot of work to get all the functionality you need.

**Comment by billonahill** [comment]
Yes, that's what I had suspected. Thanks for the prompt reply!

**Comment by ZiggerZZ** [comment]
Hi, just want to say that it'd be great if the project starts to live again.
