### ISSUE TITLE
Missing ORDER BY ABS and DATE_DIFF functions

### ISSUE THREAD

**Issue by Christos-Hadjinikolis** [Khan/tinyquery#16]
I am trying to use this to test a query of the form:

>        SELECT year_from_record, month_from_record, day_from_record
>        FROM project_id:dataset.table
>        ORDER BY ABS(DATE_DIFF(first_date_expression, second_date_expression, DAY)) ASC
>        LIMIT 1
`
I am getting a:
`
>        p = LexToken(LPAREN,'(',1,101)
>               def p_error(p):
>               raise SyntaxError('Unexpected token: %s' % p)
>               SyntaxError: Unexpected token: LexToken(LPAREN,'(',1,101)
`
intead.

**Comment by csilvers** [comment]
I don't think this is a valid legacy bigquery query.  When I type:
```
SELECT x from (SELECT 1 as x)
order by abs(x)
```
into bigquery it says:
> expression ABS([x]) in ORDER BY is invalid
and the documentation at https://cloud.google.com/bigquery/docs/reference/legacy-sql#orderby suggests that order-by only accepts field names and aliases, not functions.

It looks like tinyquery doesn't accept functions in the ORDER BY clause at all.
