### ISSUE TITLE
Transfer ownership?

### ISSUE THREAD

**Issue by csilvers** [Khan/tinyquery#21]
Hi @alangpierce !  We are not accessing bigquery from python anymore at Khan Academy, so it doesn't make sense for us to keep ownership of this project.  Would you like us to transfer it to you?

**Comment by alangpierce** [comment]
Hi @csilvers, sure, that sounds good. Feel free to send a transfer request.

**Comment by csilvers** [comment]
I'll get on it!  We have a process to go through so it may be a little bit.

**Comment by csilvers** [comment]
It's done!
