### ISSUE TITLE
Subquery ordering ignored in aggregation

### ISSUE THREAD

**Issue by sdcooke** [Khan/tinyquery#5]
On bigquery the following query returns the first item after ordering, on tinyquery the order seems to be ignored. If you point me in the right direction I could have a go at fixing this - I'm not sure I could dive in and do it straight away though!

```sql
SELECT a, FIRST(b)
FROM (
    SELECT a, b
    FROM t
    ORDER BY b
)
GROUP BY a
```

**Comment by sdcooke** [comment]
I've looked further into this and it looks like ordering is an issue when there are joins involved - trying the following query in `evaluator_test.py` orders the different columns separately causing the rows to be mixed up.

```sql
SELECT t1.val1 as v1, t1.val2 as v2, t3.foo as foo, t3.bar as bar
FROM test_table t1
JOIN test_table_3 t3 ON t1.val1 = t3.foo
ORDER BY v1, bar
```

**Comment by csilvers** [comment]
I don't know if @alangpierce is watching this repo anymore, but he'd be the one most likely to know I'm afraid!  Otherwise, you have as good a chance at figuring it out as any of us.
